language: node_js
node_js:
  - 10
after_success:
  - mkdir dist
  - cp -R frontend/src/index.html frontend/src/registration.html frontend/src/account.html frontend/src/timetable.html frontend/src/readlater.html frontend/src/tasktracker.html frontend/src/js dist frontend/src/css dist frontend/src/img dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
