language: node_js
node_js:
  - 10
after_success:
  - mkdir dist
  - cp -R src/index.html src/registration.html src/account.html src/timetable.html src/readlater.html src/tasktracker.html src/js dist src/css dist src/img dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
